# Generated by Django 4.2.30 on 2026-04-21 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('resident', 'Resident'), ('officer', 'Police Officer'), ('volunteer', 'Volunteer'), ('organisation', 'Organisation')], default='resident', max_length=20)),
                ('ward', models.CharField(blank=True, help_text='Local ward or neighbourhood', max_length=200)),
                ('badge_number', models.CharField(blank=True, help_text='For officers', max_length=20)),
                ('avatar_initials', models.CharField(blank=True, max_length=3)),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('reputation_score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reputation_score'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('concern', 'Safety Concern'), ('update', 'Police Update'), ('event', 'Community Event'), ('success', 'Success Story'), ('praise', 'Praise / Thanks'), ('volunteer', 'Volunteer Call'), ('question', 'Question'), ('alert', 'Safety Alert')], default='concern', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('replies_count', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_moderated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='crime_app.communitymember')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Crime categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Under Review', 'Under Review'), ('Acknowledged', 'Acknowledged'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved')], default='Under Review', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reporter_name', models.CharField(blank=True, max_length=200)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_phone', models.CharField(blank=True, max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('when_occurred', models.CharField(blank=True, max_length=200)),
                ('urgency', models.CharField(default='non-urgent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoliceForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('engagement_methods', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_param', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source', models.CharField(default='police-api', max_length=100)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_cleaned', models.IntegerField(default=0)),
                ('duplicates_removed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('force', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crime_app.policeforce')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('alert_type', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('force', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crime_app.policeforce')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crime_app.communitymember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeighbourhoodWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('meeting_schedule', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_watches', to='crime_app.communitymember')),
                ('force', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crime_app.policeforce')),
                ('members', models.ManyToManyField(blank=True, related_name='watch_groups', to='crime_app.communitymember')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('is_official_response', models.BooleanField(default=False, help_text='Official police response')),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='crime_app.communitymember')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='crime_app.communitypost')),
            ],
            options={
                'ordering': ['-is_official_response', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='communitymember',
            name='force',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crime_app.policeforce'),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('trend', 'Trend'), ('forecast', 'Forecast'), ('hotspot', 'Hotspot'), ('seasonal', 'Seasonal')], max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crime_app.crimecategory')),
                ('force', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crime_app.policeforce')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_app.communitymember')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='crime_app.communitypost')),
            ],
            options={
                'unique_together': {('post', 'member')},
            },
        ),
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persistent_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('location_name', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('street_name', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(db_index=True)),
                ('outcome', models.CharField(blank=True, max_length=200)),
                ('context', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField(blank=True)),
                ('is_cleaned', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='crime_app.crimecategory')),
                ('force', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='crime_app.policeforce')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'category'], name='crime_app_c_date_2d8d38_idx'), models.Index(fields=['latitude', 'longitude'], name='crime_app_c_latitud_f1ea3e_idx'), models.Index(fields=['force', 'date'], name='crime_app_c_force_i_0cae2f_idx')],
            },
        ),
    ]
